# reassemble

[![run with docker](https://img.shields.io/badge/run%20with-docker-0db7ed?labelColor=000000&logo=docker)](https://www.docker.com/)


This workflow refines a set of input bins by aligning reads back to the bins, reassembling them and outputting the highest quality bins.

## Pipeline Summary

This pipeline refines bins by aligning sequencing reads back to their corresponding bins using BWA, followed by filtering of the resulting SAM files based on strict and permissive thresholds (--strict_max & --permissive_max). Filtered reads are then used to reassemble each bin with SPAdes, which by default detects the PHRED offset automatically, but can be locked to PHRED 33 using the --lock_phred option. Reassembled bins are cleaned by removing contigs below a mimumum threshold (--min_contig). The quality of all bins both original and reassembled is assessed using CheckM2 by default, or optionally with CheckM by enabling the --checkm1 flag. The highest-quality version of each bin is selected based on minimum completeness and maximum contamination thresholds (--min_completeness & --max_contamination). 


### Parameters
- `--strict_max` (Strict bin mismatch threshold default: 2)
- `--permissive_max` (Permissive bin mismatch threshold default: 5)
- `--min_contig` (Minimum threshold for contig size kb default: 1500)
- `--min_completeness` (Minimum bin completeness threshold % default: 50)
- `--max_contamination` (Maximum bin contamination threshod % default: 5)
- `--checkm2_db` (Checkm2 database path default: /data/pam/software/checkm2_db/uniref100.KO.1.dmnd)
- `--checkm1` (Checkm default: false, uses CheckM2)
- `--lock_phred` (set PHRED quality offset to 33 when using SPAdes default: false)


### Inputs
- Set of refined bins generated by the tool Bin_refiner
- Paired-end fastqs 

### Outputs
- Set of the highest quality bins

### Dependencies
All dependencies are contained in runtime containers.


